server.port: 9100

spring:
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: java10
#    password: 123
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: elastic-service

authservice:
  secrets:
    key: ${JAVA_SECRETKEY}
    issuer: ${JAVA_ISSUER}
    exDate: 300000


